import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  camera: { flex: 1 },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 56,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  recDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#E74C3C' },
  timer: { color: '#FFFFFF', fontSize: 22, fontWeight: 'bold' },
  maxLabel: { color: 'rgba(255,255,255,0.6)', fontSize: 16 },
  progressBar: { height: 4, margin: 16, borderRadius: 2 },
  tipsBox: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    margin: 20,
    padding: 16,
    borderRadius: 12,
  },
  tipsTitle: { color: '#F39C12', fontWeight: '700', fontSize: 14, marginBottom: 8 },
  tip: { color: 'rgba(255,255,255,0.9)', fontSize: 13, lineHeight: 22 },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 32,
    paddingBottom: 40,
  },
  sideBtn: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  recordBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopBtn: { borderColor: '#E74C3C' },
  recordIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#E74C3C' },
  stopIcon: { width: 28, height: 28, borderRadius: 4, backgroundColor: '#E74C3C' },
  postRecord: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    gap: 12,
  },
  recordedLabel: { fontSize: 16, fontWeight: '600', color: '#2C3E50', textAlign: 'center' },
  errorText: { color: '#E74C3C', textAlign: 'center' },
  uploadingLabel: { fontSize: 14, color: '#7F8C8D', textAlign: 'center' },
  uploadBar: { height: 6, borderRadius: 3 },
  postActions: { flexDirection: 'row', gap: 12 },
  permissionContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, backgroundColor: '#F5F6FA' },
  permTitle: { fontSize: 20, fontWeight: 'bold', color: '#2C3E50', marginTop: 20, marginBottom: 12 },
  permSub: { fontSize: 14, color: '#7F8C8D', textAlign: 'center', marginBottom: 32, lineHeight: 22 },
  permBtn: { width: '100%', borderRadius: 10 },
});

export default styles;
