import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F6FA' },
  content: { paddingBottom: 32 },
  header: {
    backgroundColor: '#1B4F72',
    paddingTop: 56,
    paddingBottom: 24,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
  },
  greeting: { color: 'rgba(255,255,255,0.75)', fontSize: 14 },
  schoolName: { color: '#FFFFFF', fontSize: 20, fontWeight: 'bold', marginTop: 2 },
  logoutBtn: { padding: 8 },
  subBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF9E7',
    padding: 14,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F39C12',
    gap: 8,
  },
  subBannerText: { flex: 1, fontSize: 13, color: '#E67E22', fontWeight: '500' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', padding: 12, gap: 8 },
  statCard: { width: '47%', borderRadius: 12, elevation: 2 },
  statContent: { alignItems: 'center', paddingVertical: 16, gap: 6 },
  statValue: { fontSize: 20, fontWeight: 'bold' },
  statLabel: { fontSize: 12, color: '#7F8C8D', textAlign: 'center' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#2C3E50', marginHorizontal: 16, marginTop: 8, marginBottom: 12 },
  actionsGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 12, gap: 12 },
  actionCard: {
    width: '46%',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    gap: 8,
    elevation: 2,
  },
  actionIcon: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center' },
  actionLabel: { fontSize: 13, fontWeight: '600', color: '#2C3E50', textAlign: 'center' },
  jobCard: { marginHorizontal: 16, marginBottom: 8, borderRadius: 12 },
  jobContent: { flexDirection: 'row', alignItems: 'center' },
  jobTitle: { fontSize: 14, fontWeight: '600', color: '#2C3E50' },
  jobMeta: { fontSize: 12, color: '#7F8C8D', marginTop: 2 },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
});

export default styles;
