import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F6FA' },
  content: { padding: 16, paddingBottom: 40 },
  statusCard: { borderRadius: 16, marginBottom: 16, elevation: 3 },
  statusContent: { alignItems: 'center', paddingVertical: 24, gap: 10 },
  statusTitle: { fontSize: 20, fontWeight: 'bold', color: '#2C3E50' },
  planChip: { backgroundColor: '#EBF5FB' },
  expiryText: { fontSize: 13, color: '#7F8C8D' },
  statusSub: { fontSize: 14, color: '#7F8C8D', textAlign: 'center', lineHeight: 20 },
  errorBox: {
    backgroundColor: '#FDEDEC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#E74C3C',
  },
  errorText: { color: '#C0392B', fontSize: 14 },
  verifyCard: { borderRadius: 14, marginBottom: 16, borderWidth: 2, borderColor: '#F39C12' },
  verifyContent: { alignItems: 'center', gap: 10, paddingVertical: 20 },
  verifyTitle: { fontSize: 17, fontWeight: 'bold', color: '#2C3E50' },
  verifySub: { fontSize: 14, color: '#7F8C8D', textAlign: 'center', lineHeight: 20 },
  verifyBtn: { width: '100%', borderRadius: 10 },
  sectionTitle: { fontSize: 17, fontWeight: '700', color: '#2C3E50', marginBottom: 12 },
  planCard: { borderRadius: 16, marginBottom: 16, elevation: 2 },
  recommendedCard: { borderWidth: 2, borderColor: '#1B4F72' },
  recommendedBadge: {
    backgroundColor: '#1B4F72',
    alignSelf: 'flex-start',
    marginHorizontal: 16,
    marginTop: -1,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  recommendedText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  planContent: { paddingTop: 16 },
  planHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 12 },
  planName: { fontSize: 18, fontWeight: '700', color: '#2C3E50' },
  priceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
  planPrice: { fontSize: 22, fontWeight: 'bold', color: '#1B4F72' },
  planPeriod: { fontSize: 13, color: '#7F8C8D' },
  divider: { marginBottom: 12 },
  featureRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  featureText: { fontSize: 14, color: '#555', flex: 1 },
  planBtn: { borderRadius: 10, marginTop: 12 },
  disclaimer: { fontSize: 12, color: '#BDC3C7', textAlign: 'center', lineHeight: 18, marginTop: 8 },
});

export default styles;
