import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F6FA' },
  content: { padding: 16, paddingBottom: 40 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  loadingText: { color: '#7F8C8D', fontSize: 16 },
  errorBox: {
    backgroundColor: '#FDEDEC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#E74C3C',
  },
  errorText: { color: '#C0392B', fontSize: 14 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0F1',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F5F6FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#2C3E50', flex: 1 },
  section: { borderRadius: 14, marginBottom: 16, elevation: 2 },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: '#2C3E50', marginBottom: 12 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  infoLabel: { fontSize: 13, color: '#7F8C8D', width: 110 },
  infoValue: { fontSize: 13, color: '#2C3E50', fontWeight: '500', flex: 1 },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
    marginBottom: 16,
  },
  statusText: { fontSize: 13, fontWeight: '700' },
  reasonInput: { marginBottom: 12 },
  actionRow: { flexDirection: 'row', gap: 12 },
  approveBtn: { flex: 1, borderRadius: 10 },
  rejectBtn: { flex: 1, borderRadius: 10 },
  successMsg: {
    backgroundColor: '#EAFAF1',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#27AE60',
  },
  successText: { color: '#1E8449', fontSize: 14, fontWeight: '500' },
  jobRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F3F4',
  },
  jobTitle: { fontSize: 14, fontWeight: '600', color: '#2C3E50' },
  jobMeta: { fontSize: 12, color: '#7F8C8D' },
  jobDate: { fontSize: 11, color: '#BDC3C7', marginTop: 4 },
});

export default styles;
