import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F6FA' },
  content: { padding: 16, paddingBottom: 40 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  loadingText: { color: '#7F8C8D', fontSize: 16 },
  errorBox: {
    backgroundColor: '#FDEDEC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#E74C3C',
  },
  errorText: { color: '#C0392B', fontSize: 14 },
  section: { borderRadius: 14, marginBottom: 16, elevation: 2 },
  teacherRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 12 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#EBF5FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  teacherName: { fontSize: 16, fontWeight: '700', color: '#2C3E50' },
  teacherEmail: { fontSize: 13, color: '#7F8C8D', marginTop: 2 },
  teacherSubject: { fontSize: 13, color: '#1B4F72', marginTop: 2, fontWeight: '500' },
  verBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  verBadgeText: { fontSize: 12, fontWeight: '700' },
  docsRow: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  docItem: { fontSize: 13, color: '#2C3E50' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#2C3E50', marginBottom: 8 },
  sectionNote: { fontSize: 13, color: '#7F8C8D', marginBottom: 12, fontStyle: 'italic' },
  triggerRow: { flexDirection: 'row', gap: 10 },
  triggerBtn: { flex: 1, borderRadius: 10 },
  noVerifications: { alignItems: 'center', paddingVertical: 24, gap: 8 },
  noVerText: { fontSize: 14, color: '#BDC3C7' },
  divider: { marginVertical: 12 },
  verRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  verType: { fontSize: 14, fontWeight: '600', color: '#2C3E50', marginBottom: 4 },
  verMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  verStatus: { fontSize: 12, color: '#7F8C8D', fontWeight: '500' },
  verDate: { fontSize: 12, color: '#BDC3C7' },
  verNotes: { fontSize: 12, color: '#7F8C8D', fontStyle: 'italic', marginTop: 4 },
  resultBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
  resultText: { fontSize: 11, fontWeight: '700' },
  manualOverride: { backgroundColor: '#F8F9FA', borderRadius: 10, padding: 12, marginTop: 8, gap: 8 },
  overrideLabel: { fontSize: 13, fontWeight: '600', color: '#2C3E50' },
  resultOptions: { flexDirection: 'row', gap: 8 },
  notesInput: { marginTop: 4 },
  submitOverrideBtn: { borderRadius: 8, marginTop: 4 },
  adminActions: { gap: 10 },
  adminBtn: { borderRadius: 10 },
});

export default styles;
